const fs = require('fs');

// Brief tafsir summaries for each surah (by revelation order)
const tafsirMap = [
    // 1-10 Mekke erken
    { tr: "İnsanın Allah tarafından yaratıldığını ve O'nun adıyla okumanın emredildiğini bildirir. İlim ve kalem üzerine vurgu yapar.", en: "Proclaims that man was created by God and commands reading in His name. Emphasizes knowledge and the pen." },
    { tr: "Ahlak ve karakter üzerine inen bu sure, Peygamber'in üstün ahlakını ve inançsızların tutumunu ele alır.", en: "Revealed about character, this surah addresses the Prophet's excellent morality and the stance of disbelievers." },
    { tr: "Peygamber'e gecenin ibadetini emreder; sabır ve tevekkülü öğütler.", en: "Commands the Prophet to worship at night; teaches patience and trust in God." },
    { tr: "Peygamber'e insanları uyarma görevini verir; her insanın ameline karşılık alacağını bildirir.", en: "Assigns the Prophet the duty to warn people; states that everyone will receive what they have earned." },
    { tr: "Kur'an'ın özeti sayılır; Allah'a hamd, yalnızca O'na ibadet ve doğru yola kılavuzluk için dua içerir.", en: "Considered the essence of the Quran; contains praise of God, worship of Him alone, and prayer for guidance." },
    { tr: "Ebu Leheb ve karısının Peygambere düşmanlığı yüzünden yok olacağını bildirir.", en: "Declares that Abu Lahab and his wife will perish due to their enmity toward the Prophet." },
    { tr: "Kıyamet gününü ve yıldızların söneceğini, göğün yarılacağını anlatır.", en: "Describes the Day of Judgment: stars will be extinguished and the sky will split." },
    { tr: "İnsanı yüksek ahlaka davet eder; Allah'ın adını tesbih etmeyi emreder.", en: "Invites man to high morality; commands glorification of God's name." },
    { tr: "Gecenin ve gündüzün farklı işlevleri üzerinden cömertlik ile cimriliğin sonuçlarını anlatır.", en: "Through the contrast of night and day, describes the consequences of generosity and miserliness." },
    { tr: "Kıyamet gününün dehşetini ve insan ruhunun hesaba çekileceğini anlatır.", en: "Describes the awe of the Day of Judgment and the soul's reckoning." },
    // 11-20
    { tr: "Sabah aydınlığı ve geceye yemin ederek Peygamber'i teselli eder; Allah'ın nimetlerini saymayı emreder.", en: "Comforts the Prophet by the morning light and the night; commands counting God's blessings." },
    { tr: "Peygamber'in sıkıntısının giderildiğini bildirir; zorlukla birlikte kolaylık olduğunu vurgular.", en: "Declares the Prophet's distress relieved; emphasizes that with hardship comes ease." },
    { tr: "Zamana yemin ederek insanın hüsranda olduğunu; iman, amel, hak ve sabırla kurtuluşa ereceğini bildirir.", en: "Swearing by time, states man is in loss; salvation is through faith, good deeds, truth and patience." },
    { tr: "Dünya hırsının, koşturup duran insanı nasıl oyaladığını ve hesap gününü hatırlatır.", en: "Reminds how worldly greed distracts restless man, and warns of the day of reckoning." },
    { tr: "Peygamber'e Kevser nehrini müjdeler; düşmanlarının asıl yoksul ve ebtersiz olanlar olduğunu bildirir.", en: "Gives the Prophet glad tidings of Al-Kawthar; states his enemies are truly the ones cut off." },
    { tr: "Dünyalık ile övünmenin insanı nasıl oyaladığını; kabirleri ziyarete kadar gaflet içinde yaşandığını anlatır.", en: "Describes how rivalry in worldly things distracts man; he lives in heedlessness until he visits the graves." },
    { tr: "Dini yalanlayanı tasvir eder: yetimi kovan, yoksulu doyurmayan kişidir.", en: "Portrays the one who denies the faith: one who drives away the orphan and does not feed the poor." },
    { tr: "İnkârcılara hitap eder; onların diniyle Müslümanların dininin birbirinden farklı olduğunu beyan eder.", en: "Addresses the disbelievers; declares that their religion and the Muslims' religion are distinct from one another." },
    { tr: "Mekke'yi fetheden fil ordusunun nasıl helak edildiğini anlatır.", en: "Describes how the army of elephants marching on Mecca was destroyed." },
    { tr: "Her türlü şerden Allah'a sığınmayı, özellikle sihir ve haset şerrinden korunmayı öğretir.", en: "Teaches seeking refuge in God from all evil, especially magic and envy." },
    // 21-30
    { tr: "İnsanın şeytanı ve vesveselerinden Allah'a sığınmasını öğretir.", en: "Teaches man to seek refuge in God from Satan and evil whisperings." },
    { tr: "Allah'ın tekliğini, doğurmadığını ve doğurulmadığını ifade eden tevhidin özüdür.", en: "The essence of monotheism: God is One, He neither begets nor is begotten." },
    { tr: "İsra ve Mi'rac sırasında görülen işaretleri anlatır; melekler ve Allah'ın yüceliğini tasvir eder.", en: "Describes signs seen during the Night Journey; depicts angels and the majesty of God." },
    { tr: "Peygamber'in kör sahabiyi görmezden gelmesini eleştirir; Kur'an'ın hatırlatıcı olduğunu vurgular.", en: "Admonishes the Prophet for ignoring the blind man; emphasizes the Quran as a reminder." },
    { tr: "Kadir gecesinin bin aydan hayırlı olduğunu ve meleklerin indiğini bildirir.", en: "Declares the Night of Power is better than a thousand months and that angels descend." },
    { tr: "Güneş, ay ve insan ruhuna yemin ederek nefsini arındıranın kurtuluşa erdiğini bildirir.", en: "Swearing by sun, moon, and soul, declares that he who purifies his soul will prosper." },
    { tr: "Gökten aşağı yakın olan burçlara yemin ederek mü'minleri ateşe atan Ashab-ı Uhdud'u anlatır.", en: "Swearing by the constellations, tells of the People of the Trench who cast believers into fire." },
    { tr: "İncir ve zeytine yemin ederek insanın en güzel biçimde yaratıldığını, sonra aşağıların en aşağısına düşürüldüğünü bildirir.", en: "Swearing by the fig and olive, states man was created in the best form, then reduced to the lowest of the low." },
    { tr: "Kureyş'e, Kâbe'ye hizmet sayesinde elde ettikleri yiyecek ve güvenlik nimetlerini hatırlatır.", en: "Reminds Quraysh of the blessings of food and security they gained through their service to the Kaaba." },
    { tr: "Kıyamet gününde yaşanacakları ve günahkârların hesabını anlatır.", en: "Describes events of the Day of Judgment and the reckoning of sinners." },
    // 31-40
    { tr: "Kıyamet gününü anlatır; kaçış olmadığını, Allah'ın her şeyi bilen olduğunu vurgular.", en: "Describes the Day of Judgment; emphasizes there is no escape and God knows all things." },
    { tr: "Dünya malıyla övünmenin, sürekli biriktirmenin tehlikesine dikkat çeker.", en: "Warns against boasting about worldly wealth and the danger of constant accumulation." },
    { tr: "İnsanların kıyamette Allah'a karşı hesap vereceğini ve cennet ile cehennemin varlığını anlatır.", en: "Describes man's reckoning before God on the Day of Judgment and the reality of paradise and hell." },
    { tr: "Kaf harfiyle başlar; kıyamet ve dirilişi anlatır; insanın her hareketini izleyen melekleri tasvir eder.", en: "Opens with Qaf; describes resurrection and the Day of Judgment; depicts angels recording every human act." },
    { tr: "Hac ve Allah yolunda cihad ibadeti hakkında ayrıntılı hükümler içerir.", en: "Contains detailed rulings on the Hajj pilgrimage and striving in God's path." },
    { tr: "İnsanın pis bir sudan yaratıldığını, kıyamette her şeyin hesaba çekileceğini anlatır.", en: "States man was created from a humble fluid; on the Day of Judgment everything will be called to account." },
    { tr: "Kâfirleri reddetmeye ve Allah'a tevekkül etmeye davet eder.", en: "Invites the Prophet to reject the disbelievers and put trust in God." },
    { tr: "Yaratılışın delilleriyle Allah'ın varlığını kanıtlar; Peygamber'in kaygılarını teselli eder.", en: "Proves God's existence through the signs of creation; consoles the Prophet's concerns." },
    { tr: "Kıyamet anını ve üç grubun (öncüler, sağcılar, solcular) durumunu anlatır.", en: "Describes the moment of resurrection and the state of three groups: the foremost, the righteous, and the wretched." },
    { tr: "Şairlerin ve şiirin hükmünü, Peygamber'in şair olmadığını açıklar.", en: "Explains the ruling on poets and poetry, and clarifies that the Prophet is not a poet." },
    { tr: "Cin suresinde cinlerin Kur'an'ı dinleyip iman etmelerini ve elçilerini anlatır.", en: "Describes jinns listening to the Quran, believing, and telling their people about this messenger." },
    // 41-50
    { tr: "Ya Sin harfleriyle başlar; Kur'an'ın hikmetinden, kıyametten ve diriliş delillerinden söz eder.", en: "Opens with Ya Sin; speaks of the wisdom of the Quran, the Day of Judgment, and proofs of resurrection." },
    { tr: "Hakkı batıldan ayıran Kur'an'ın özelliklerini anlatır; geçmiş peygamberlerin kıssalarına değinir.", en: "Describes the characteristics of the Quran that distinguishes truth from falsehood; refers to stories of past prophets." },
    { tr: "Allah'ın varlığının delillerini sayar; inkârcıların azabını anlatır.", en: "Lists evidence of God's existence; describes the punishment of the disbelievers." },
    { tr: "Hz. Meryem'in doğumu, Hz. Yahya ve Hz. İsa'nın doğumunu ve çeşitli peygamberlerin kıssalarını anlatır.", en: "Narrates the birth of Mary, John the Baptist, and Jesus, along with stories of various prophets." },
    { tr: "Hz. Musa'nın vahiy alması, nübüvveti ve İsrailoğulları ile ilgili olayları anlatır.", en: "Narrates Moses receiving revelation, his prophethood, and events related to the Children of Israel." },
    { tr: "Kıyameti anlatır; o gün insanların üç sınıfa ayrılacağını bildirir.", en: "Describes the Day of Judgment; declares that people will be divided into three classes on that day." },
    { tr: "Şuara peygamberlerin etkili konuşmalarını anlatır; onları şairlerden ayırt eder.", en: "Narrates the powerful speeches of the prophets in Shu'ara; distinguishes them from poets." },
    { tr: "Neml suresinde Hz. Süleyman ile Sebe Melikesi Belkıs'ın kıssasını ve karınca mucizesini anlatır.", en: "In Naml, narrates the story of Solomon and the Queen of Sheba, Bilqis, and the miracle of the ant." },
    { tr: "Hz. Musa'nın doğumunu, gençliğini ve Firavun'la mücadelesini anlatır.", en: "Narrates Moses' birth, youth, and struggle against Pharaoh." },
    { tr: "Peygamber'in Mekke'den Medine'ye hicret öncesi gece yolculuğunu (İsra) anlatır.", en: "Describes the Prophet's night journey (Isra) from Mecca to Jerusalem before his migration to Medina." },
    // 51-60
    { tr: "Allah'ın birliğini reddeden Mekke müşriklerini uyarır; geçmiş kavimlerin helakını hatırlatır.", en: "Warns Meccan polytheists who deny God's unity; reminds them of the destruction of past peoples." },
    { tr: "Hz. Nuh, Hz. Hud, Hz. Salih, Hz. İbrahim ve diğer peygamberlerin kıssalarını anlatır.", en: "Narrates stories of Noah, Hud, Salih, Abraham and other prophets." },
    { tr: "Hz. Yusuf'un hayatını başından sonuna kadar eksiksiz anlatır.", en: "Tells the complete story of Joseph from beginning to end." },
    { tr: "Müminler, münafıklar ve kâfirler üç grup olarak ele alınır; Hicr vadisi halkı ve Hz. İbrahim anlatılır.", en: "Three groups are addressed: believers, hypocrites, disbelievers; the people of Hijr and Abraham are narrated." },
    { tr: "Evreni ve içindeki nimetleri sıralayarak Allah'ın yüceliğini ispat eder; inanmayanlardan hesap sorulacağını bildirir.", en: "Lists the universe's blessings to prove God's majesty; states the disbelievers will be called to account." },
    { tr: "Kıyamete yemin ederek insanın kendi nefsine karşı tanık olduğunu bildirir.", en: "Swearing by the Day of Resurrection, states that man is a witness against his own soul." },
    { tr: "İbrahim başta olmak üzere peygamberlerin kıssalarını anlatır; sonunda putperestleri uyarır.", en: "Narrates stories of prophets, especially Abraham; at the end warns the polytheists." },
    { tr: "Doğa ve tarih delilleriyle Allah'ın birliğini kanıtlar; inançsızları uyarır.", en: "Proves God's unity through natural and historical evidence; warns the disbelievers." },
    { tr: "Zümer başlığı insanların ahiretteki gruplarını (cehennemlikler ve cennetlikler) anlatır.", en: "Zumar describes groups of people in the afterlife (those destined for hell and paradise)." },
    { tr: "Müminlerin özelliklerini ve inkârcıların tutumunu anlatır; Allah'a dua ve teslimiyeti öğütler.", en: "Describes characteristics of believers and the attitude of disbelievers; urges prayer and surrender to God." },
    // 61-70
    { tr: "Kur'an'ın apaçık kitap olduğunu; Hz. Musa ve Hz. İsa'ya değinir.", en: "States the Quran is a clear book; refers to Moses and Jesus." },
    { tr: "Vahyin nasıl indiğini, şura (danışma) ilkesini ve iman esaslarını anlatır.", en: "Describes how revelation descends, the principle of consultation (shura), and articles of faith." },
    { tr: "Altın süslemelere sahip olmanın gerçek mutluluk olmadığını; ahiret nimetlerinin üstünlüğünü anlatır.", en: "States that golden adornments are not true happiness; emphasizes the superiority of the hereafter's blessings." },
    { tr: "Duman (Duhan) azabından ve inkârcıların durumundan söz eder; Hz. Musa ve Firavun kıssasını işler.", en: "Speaks of the punishment of smoke (Dukhan) and the state of disbelievers; addresses the story of Moses and Pharaoh." },
    { tr: "Allah'ın evrendeki delillerini sıralar; inkârcıların helak olduğu toplumların kıssalarını anlatır.", en: "Lists God's signs in the universe; tells the stories of communities destroyed for disbelief." },
    { tr: "Hak ile batıl arasındaki mücadeleyi anlatır; imanın önemi ve inananların tutumu ele alınır.", en: "Narrates the struggle between truth and falsehood; discusses the importance of faith and believers' stance." },
    { tr: "Esen rüzgârlara yemin ederek kıyamet ve geçmiş kavimlerin helakını anlatır.", en: "Swearing by the scattering winds, describes the Day of Judgment and the destruction of past peoples." },
    { tr: "Allah'ın nimetlerini (Rahman) sıralar; her nimet sonrasında 'Rabbinizin hangi nimetlerini yalanlarsınız?' diye sorar.", en: "Lists God's blessings (the Most Merciful); after each blessing asks, 'Which of your Lord's favors will you deny?'" },
    { tr: "İnsana ve Allah'ın nimetlerine şükretmeyi öğütler; insan ve toplumun sorumluluklarını bildirir.", en: "Urges gratitude to man and for God's blessings; states the responsibilities of the individual and society." },
    { tr: "Boşanma ile ilgili hukuki düzenlemeler ve evlilik hayatındaki adalet kurallarını bildirir.", en: "Prescribes legal regulations regarding divorce and rules of justice in married life." },
    // 71-80
    { tr: "Hz. Nuh'un kavmini iman etmeye nasıl davet ettiğini ve sonunda beddua edip gemiye bindiğini anlatır.", en: "Narrates how Noah invited his people to faith and finally cursed them and boarded the ark." },
    { tr: "Hz. İbrahim'in putperestlere karşı mücadelesi ve oğlu İsmail ile Kâbe'yi inşasını anlatır.", en: "Narrates Abraham's struggle against idolaters and his building of the Kaaba with his son Ishmael." },
    { tr: "Geçmiş peygamberlerin kıssaları üzerinden Allah'ın her toplumu uyardığını ve inkârcıların helak olduğunu anlatır.", en: "Through stories of past prophets, shows God warned every community and the disbelievers perished." },
    { tr: "İman eden erkek ve kadının özelliklerini sayar; inkârcıların durumunu ele alır.", en: "Lists qualities of believing men and women; addresses the state of the disbelievers." },
    { tr: "Kıyameti ve insanların ruhlarının alınmasını anlatır; secde ayeti içerir.", en: "Describes the Day of Judgment and the taking of souls; contains a verse of prostration." },
    { tr: "Tur Dağı'na yemin ederek kıyameti anlatır; inkârcıları uyarır.", en: "Swearing by Mount Tur, describes the Day of Judgment; warns the disbelievers." },
    { tr: "Mülkün (egemenliğin) yalnız Allah'a ait olduğunu anlatır; ölüm ve hayatın imtihan için yaratıldığını bildirir.", en: "States that dominion belongs to God alone; declares that death and life were created as a test." },
    { tr: "Kıyamet günü yaşananları anlatır; cehennem azabı ve cennet nimetlerini tasvir eder.", en: "Describes the events of the Day of Judgment; depicts the torment of hell and the blessings of paradise." },
    { tr: "Kıyamet için yemin ederek ruhun Allah'a döneceğini; herkesin amelinden sorumlu olduğunu bildirir.", en: "Swearing by the Day of Judgment, states the soul will return to God; everyone is responsible for their deeds." },
    { tr: "Büyük haberi (kıyameti) anlatır; insanı bu günden önce hazırlanmaya davet eder.", en: "Narrates the great news (the Day of Judgment); invites man to prepare before that day." },
    // 81-90
    { tr: "Ruhları alan melekleri anlatır; kıyamet anını tasvir eder.", en: "Describes the angels who take souls; depicts the moment of resurrection." },
    { tr: "Göğün yarılmasını ve Allah'a hesap vermeyi anlatır.", en: "Describes the splitting of the sky and giving account before God." },
    { tr: "Ölçü ve tartıda hile yapanları uyarır; ahiretteki azabı haber verir.", en: "Warns those who cheat in weights and measures; announces the punishment in the hereafter." },
    { tr: "Göğün yarılıp insan ruhunun Allah'a döneceğini anlatır.", en: "Describes the sky splitting open and the human soul returning to God." },
    { tr: "Hz. İbrahim ve Hz. Musa'nın kıssaları ile kıyamet gününe dair uyarılar içerir.", en: "Contains warnings about the Day of Judgment and the stories of Abraham and Moses." },
    { tr: "Tarih boyunca Allah'a karşı çıkan toplumların ibret verici kıssalarını anlatır.", en: "Narrates cautionary tales of communities throughout history that opposed God." },
    { tr: "İman ile ameli birleştirmenin önemi ve Medine toplumunun ortak sorumlulukları ele alınır.", en: "The importance of combining faith with action and the shared responsibilities of the Medinan community." },
    { tr: "Allah'ın varlığının delillerini anlatır; Peygamber'i inkâr etmemenin önemini vurgular.", en: "Narrates proof of God's existence; emphasizes the importance of not denying the Prophet." },
    { tr: "Müminlerin ibadet anlayışı, İslam'da hayatı düzenleyen kurallar ele alınır.", en: "Addresses believers' understanding of worship and rules that organize life in Islam." },
    { tr: "Münafıklar ve onların özelliklerini anlatır; onları Allah'a karşı uyarır.", en: "Describes the hypocrites and their characteristics; warns them against God." },
    // 91-100
    { tr: "Birbirinizi Hakk'a ve sabra tavsiye etmeyi emreder; cemaat ruhunu güçlendirir.", en: "Commands recommending truth and patience to one another; strengthens the spirit of community." },
    { tr: "Medine toplumunda müminlerin savaş ve barış güçlerini ele alır; cihad ve sabır emini işler.", en: "Addresses the military and peace forces of believers in Medinan society; covers jihad and patience." },
    { tr: "Dini terketmeye veya İslam'la çelişen iddialara karşı uyarır; münafıkları ve inançsızları ele alır.", en: "Warns against abandoning the faith or claims conflicting with Islam; addresses hypocrites and disbelievers." },
    { tr: "Mümin bir kadının Allah'ın rızasını kazanmak için kocasını şikâyet etmesini anlatır; adalet ilkesini işler.", en: "Narrates a believing woman complaining to God about her husband to seek His pleasure; addresses justice." },
    { tr: "Düşmanlarla bile adil davranmayı öğretir; hicret edenleri müjdeler.", en: "Teaches fair treatment even toward enemies; gives glad tidings to those who emigrate." },
    { tr: "Kadınların haklarını, miras ve aile hukukunu düzenleyen kapsamlı ayetler içerir.", en: "Contains comprehensive verses regulating women's rights, inheritance, and family law." },
    { tr: "İnsanın yaratılışını ve Allah'ın nimetini hatırlatan bu sure, kıyametteki hesabı anlatır.", en: "This surah reminds of man's creation and God's blessing, and describes the reckoning on the Day of Judgment." },
    { tr: "Uhud savaşını ve müminlerin bu savaştaki tutumunu, şehitliği ele alır.", en: "Addresses the Battle of Uhud, the believers' stance in that battle, and martyrdom." },
    { tr: "İslam devletinin kural ve düzenlemelerini; müminlerin birlik ve dayanışmasını ele alır.", en: "Addresses the rules and regulations of the Islamic state; the unity and solidarity of believers." },
    { tr: "Enfal, Bedir savaşı ganimetlerini ve müminlerin bu süreçteki tutumunu ele alır.", en: "Al-Anfal addresses the war gains of Badr and believers' attitudes in this process." },
    // 101-114
    { tr: "Hendek Savaşı (Ahzab) bağlamında münafıkları eleştirir; Peygamber'in eşleriyle ilgili özel hükümler içerir.", en: "In the context of the Battle of the Trench, criticizes hypocrites; contains special rulings about the Prophet's wives." },
    { tr: "Mümin olduğunu iddia edip ihanet eden kadın veya erkeğin Allah yolunda terk edilmesini emreder.", en: "Commands abandoning women or men who claim to be believers but betray, in the way of God." },
    { tr: "Medine toplumunun temel ahlak kurallarını ve İslam devletinin siyasi yapısını düzenler.", en: "Regulates the fundamental moral rules of the Medinan community and the political structure of the Islamic state." },
    { tr: "Cuma namazının önemini anlatır; ticarete koşarak Cuma'yı terk etmeyi yasaklar.", en: "Describes the importance of Friday prayer; prohibits abandoning Friday prayer to rush to trade." },
    { tr: "Münafıkların iç yüzünü anlatır; İslam camiasına zarar vermeye çalışan bu gruba dikkat çeker.", en: "Describes the true nature of the hypocrites; draws attention to this group trying to harm the Muslim community." },
    { tr: "İlahi yasakları çiğnemeyi önler; kocasına zıhar yapan kadın için kefaret kurallarını bildirir.", en: "Prevents violating divine prohibitions; announces atonement rules for the woman who has made zihar to her husband." },
    { tr: "Allah yolunda hicret edenleri müjdeler ve düşmanlarla dahi adil davranmayı emreder.", en: "Gives glad tidings to those who emigrate for God's sake and commands just treatment even toward enemies." },
    { tr: "Müslümanların savaşta kararlı olmasını öğütler; tam bağlılık ve birliği emreder.", en: "Encourages Muslims to be steadfast in battle; commands complete devotion and unity." },
    { tr: "Mekke'nin fethini müjdeler; bu zaferin Allah'ın yardımıyla gerçekleştiğini bildirir.", en: "Announces the conquest of Mecca; declares this victory came with God's help." },
    { tr: "Allah'ın nimetini anlatır; beş temel farzdaki (helal yiyecek dahil) hükümleri bildirir.", en: "Describes God's blessing; announces rulings in the five fundamental obligations (including lawful food)." },
    { tr: "Mekke'nin fethinden sonra putperestlerle ilişkileri keser; İslam'ı kabul etmeyenlere süre tanır.", en: "Severs relations with polytheists after the conquest of Mecca; gives time to those who do not accept Islam." },
    { tr: "Allah'ın yardımı ve fetih geldiğinde hamd edilmesini ve tövbe edilmesini emreder.", en: "Commands praising God and seeking repentance when God's help and victory arrive." },
];

const currentData = JSON.parse(fs.readFileSync(__dirname + '/../src/data/quranChronology.json', 'utf-8'));

const enriched = currentData.map((item, i) => ({
    ...item,
    tafsir: tafsirMap[i] || { tr: item.context?.tr || '', en: item.context?.en || '' },
}));

fs.writeFileSync(
    __dirname + '/../src/data/quranChronology.json',
    JSON.stringify(enriched, null, 2)
);
console.log(`✅ Added tafsir to ${enriched.length} surahs`);
