const fs = require('fs');

const surahs = [
    [1, 96, "العلق", "Al-Alaq", "Alak", "Mekke", "610 M.", "96:1-5", "First revelation in Cave of Hira – command to read", "Peygamberimize (s.a.s) Hira Mağarası'nda gelen ilk vahiy: 'Oku!'"],
    [2, 68, "القلم", "Al-Qalam", "Kalem", "Mekke", "610 M.", "68:1-52", "Prophet's character defended against Quraysh mockery", "Kureyş'in hakaretlerine karşı Peygamberimizin ahlakı savunuldu"],
    [3, 73, "المزمل", "Al-Muzzammil", "Müzzemmil", "Mekke", "610 M.", "73:1-20", "Command for night prayer to strengthen the Prophet", "Zor dönemde gece ibadetiyle manevi güç inşası emredildi"],
    [4, 74, "المدثر", "Al-Muddaththir", "Müddessir", "Mekke", "610 M.", "74:1-56", "Command to arise and warn the people", "Kamuoyunu uyarma emri: 'Kalk ve uyar!'"],
    [5, 1, "الفاتحة", "Al-Fatiha", "Fatiha", "Mekke", "611 M.", "1:1-7", "Opening surah – foundation of Islamic prayer", "Namazın temeli; Kuran'ın özeti"],
    [6, 111, "المسد", "Al-Masad", "Tebbet", "Mekke", "612 M.", "111:1-5", "Abu Lahab condemned for opposing Islam", "Amcası Ebu Leheb'in İslam'a düşmanlığı üzerine indi"],
    [7, 81, "التكوير", "At-Takwir", "Tekvir", "Mekke", "612 M.", "81:1-29", "Vivid description of the Day of Judgment", "Kıyamet gününün dramatik tasviri"],
    [8, 87, "الأعلى", "Al-A'la", "A'la", "Mekke", "612 M.", "87:1-19", "Glorify your Lord – ease in remembrance", "'Rabbinin adını tesbih et' – hatırlamanın kolaylaştırılması"],
    [9, 92, "الليل", "Al-Layl", "Leyl", "Mekke", "612 M.", "92:1-21", "Night oath – reward for charity and piety", "Gece yeminiyle cömertlik ve takvanın mükafatı"],
    [10, 89, "الفجر", "Al-Fajr", "Fecr", "Mekke", "613 M.", "89:1-30", "Dawn oath – fate of Ad, Thamud, Pharaoh", "Ad, Semud ve Firavun'un helaki; adil şahit Allah"],
    [11, 93, "الضحى", "Ad-Duha", "Duha", "Mekke", "613 M.", "93:1-11", "Revelation paused – God reassures the Prophet", "Vahyin kesilmesi üzerine Allah'ın Peygamberi tesellisi"],
    [12, 94, "الشرح", "Al-Inshirah", "İnşirah", "Mekke", "613 M.", "94:1-8", "After hardship comes ease – twice promised", "Her güçlükle birlikte kolaylık vardır – iki kez vaat"],
    [13, 103, "العصر", "Al-Asr", "Asr", "Mekke", "613 M.", "103:1-3", "Time oath – humanity in loss except believers", "Zaman yemini: iman-amel-sabır olmadan insan zarardadır"],
    [14, 100, "العاديات", "Al-Adiyat", "Adiyat", "Mekke", "613 M.", "100:1-11", "War horses imagery – human ingratitude", "Savaş atlarıyla yeminden insan nankörlüğüne geçiş"],
    [15, 108, "الكوثر", "Al-Kawthar", "Kevser", "Mekke", "613 M.", "108:1-3", "River of abundance given to the Prophet", "Peygambere Kevser havuzu müjdelendi; düşmanı soyu kesik"],
    [16, 102, "التكاثر", "At-Takathur", "Tekasür", "Mekke", "614 M.", "102:1-8", "Warning against competing in worldly wealth", "Dünya malı yarışına karşı uyarı: kabre kadar sürsün mu?"],
    [17, 107, "الماعون", "Al-Ma'un", "Maun", "Mekke", "614 M.", "107:1-7", "Those who deny judgment neglect prayer and charity", "Dini yalanlayanlar: yetimi iter, namazı savsaklar"],
    [18, 109, "الكافرون", "Al-Kafiroon", "Kafiroon", "Mekke", "614 M.", "109:1-6", "Clear declaration: your religion for you, mine for me", "Müşriklerin uzlaşı teklifine net cevap: 'Sizin dininiz size'"],
    [19, 105, "الفيل", "Al-Fil", "Feel", "Mekke", "614 M.", "105:1-5", "Abraha's elephant army destroyed at Mecca", "Kabe'ye saldıran Ebehe ordusu kuşlarla helak edildi"],
    [20, 113, "الفلق", "Al-Falaq", "Felak", "Mekke", "614 M.", "113:1-5", "Seek refuge from external evils", "Dış kötülüklere karşı Allah'a sığınma"],
    [21, 114, "الناس", "An-Nas", "Nas", "Mekke", "614 M.", "114:1-6", "Seek refuge from inner whisperings", "İç vesvesciye karşı Allah'a sığınma"],
    [22, 112, "الإخلاص", "Al-Ikhlas", "İhlas", "Mekke", "615 M.", "112:1-4", "Pure monotheism – God is One, eternal", "Tevhidin özü: Allah Ehaddir, Sameddir"],
    [23, 53, "النجم", "An-Najm", "Necm", "Mekke", "615 M.", "53:1-62", "Prophet's Mi'raj vision described", "Miraç'ta görülenler; putların gerçeği"],
    [24, 80, "عبس", "Abasa", "Abese", "Mekke", "615 M.", "80:1-42", "Prophet frowned at blind man's interruption", "Peygamberin kör ile meşgul olmaması üzerine inen vahiy"],
    [25, 97, "القدر", "Al-Qadr", "Kadir", "Mekke", "615 M.", "97:1-5", "Night of Power – better than a thousand months", "Kadir Gecesi'nin müjdesi: bin aydan hayırlı"],
    [26, 91, "الشمس", "Ash-Shams", "Şems", "Mekke", "615 M.", "91:1-15", "Sun oath – purify your soul or perish", "Güneş yemini: nefsi arındıranlar kurtuluşa erişti"],
    [27, 85, "البروج", "Al-Buruj", "Buruc", "Mekke", "615 M.", "85:1-22", "Companions of the Trench martyred for faith", "İman yüzünden ateş çukuruna atılan mü'minler"],
    [28, 95, "التين", "At-Tin", "Tin", "Mekke", "615 M.", "95:1-8", "Fig and olive oath – best human form", "İncir-zeytin yemini: insan en güzel biçimde yaratıldı"],
    [29, 106, "قريش", "Quraysh", "Kureyş", "Mekke", "615 M.", "106:1-4", "Quraysh given trade routes – worship God", "Kureyş'e verilen kış-yaz yolculuk nimeti; şükür emri"],
    [30, 101, "القارعة", "Al-Qaria", "Karia", "Mekke", "615 M.", "101:1-11", "The Calamity – scales of deeds", "Çarpıcı saat: ameller tartılacak, ağır basan kurtuluşta"],
    [31, 75, "القيامة", "Al-Qiyama", "Kıyamet", "Mekke", "616 M.", "75:1-40", "Human soul will testify against itself", "Kıyamet günü nefs kendi aleyhine şahitlik edecek"],
    [32, 104, "الهمزة", "Al-Humazah", "Hümeze", "Mekke", "616 M.", "104:1-9", "Woe to every slanderer and backbiter", "Arkadan çekiştirip mal yığanların akıbeti"],
    [33, 77, "المرسلات", "Al-Mursalat", "Mürselat", "Mekke", "616 M.", "77:1-50", "Winds sent forth – repeated warning", "Azap inkarcılara: 'O gün yalanlayanların vay haline!'"],
    [34, 50, "ق", "Qaf", "Kaf", "Mekke", "616 M.", "50:1-45", "Quran as proof – Day of Resurrection", "Kur'an hakikatinin delili; dirilişi inkara cevap"],
    [35, 90, "البلد", "Al-Balad", "Beled", "Mekke", "616 M.", "90:1-20", "The Holy City – uphill road of virtue", "Mekke'yi şahit göstererek erdemli yolu tutma çağrısı"],
    [36, 86, "الطارق", "At-Tariq", "Tarık", "Mekke", "616 M.", "86:1-17", "Piercing star – every soul has a guardian", "Gökteki sabah yıldızı yemini; her nefse bekçi"],
    [37, 54, "القمر", "Al-Qamar", "Kamer", "Mekke", "616 M.", "54:1-55", "Moon split miracle – Quraysh deny signs", "Ay'ın yarılması mucizesi; Kureyş'in mucizeyi reddetmesi"],
    [38, 38, "ص", "Sad", "Sad", "Mekke", "617 M.", "38:1-88", "David and Solomon's wisdom – Prophet's steadfastness", "Davud ve Süleyman'ın hikmetli kıssaları"],
    [39, 7, "الأعراف", "Al-A'raf", "A'raf", "Mekke", "617 M.", "7:1-206", "Detailed stories of prophets and their nations", "Hud, Salih, Lut, Şuayb peygamberlerin kıssaları"],
    [40, 72, "الجن", "Al-Jinn", "Cin", "Mekke", "617 M.", "72:1-28", "Jinn who heard the Quran and believed", "Cin topluluğunun Kuran'ı duyup iman etmesi"],
    [41, 36, "يس", "Ya-Sin", "Ya Sin", "Mekke", "617 M.", "36:1-83", "Heart of the Quran – resurrection proof", "'Kuran'ın kalbi'; diriliş ve vahyin hakikati"],
    [42, 25, "الفرقان", "Al-Furqan", "Furkan", "Mekke", "617 M.", "25:1-77", "The Criterion – Quran separates truth from falsehood", "Hak ile batılı ayıran ölçüt; müşriklerin itirazlarına cevap"],
    [43, 35, "فاطر", "Fatir", "Fatır", "Mekke", "617 M.", "35:1-45", "The Originator – angels as messengers", "Yaratıcı Allah; melekler ve kainatın düzeni"],
    [44, 19, "مريم", "Maryam", "Meryem", "Mekke", "617 M.", "19:1-98", "Story of Mary and Jesus – revealed before Abyssinia migration", "Meryem ve İsa kıssası; Habeşistan göçü öncesi indi"],
    [45, 20, "طه", "Ta-Ha", "Ta-Ha", "Mekke", "617 M.", "20:1-135", "Moses detailed story – comfort for Prophet", "Hz. Musa'nın ayrıntılı hayatı; Peygambere sabır dersi"],
    [46, 56, "الواقعة", "Al-Waqia", "Vakıa", "Mekke", "617 M.", "56:1-96", "Three groups on Judgment Day", "Kıyamette üç grup: öncüler, sağ taraftakiler, sol taraftakiler"],
    [47, 26, "الشعراء", "Ash-Shuara", "Şuara", "Mekke", "618 M.", "26:1-227", "Moses, Abraham, Noah – poets who follow desires", "Peygamberlerin kıssaları; hakkı söyleyen şairler"],
    [48, 27, "النمل", "An-Naml", "Neml", "Mekke", "618 M.", "27:1-93", "Solomon and Queen of Sheba – ant valley", "Süleyman ile Sebe Melikesi; karıncaların vadisi"],
    [49, 28, "القصص", "Al-Qasas", "Kasas", "Mekke", "618 M.", "28:1-88", "Full story of Moses from birth to prophethood", "Musa'nın doğumundan peygamberliğe tam hayat hikayesi"],
    [50, 17, "الإسراء", "Al-Isra", "İsra", "Mekke", "619 M.", "17:1-111", "Night Journey – Isra and Mi'raj miracle", "Miraç mucizesi; Peygamberin Mescid-i Haram'dan Aksa'ya yolculuğu"],
    [51, 10, "يونس", "Yunus", "Yunus", "Mekke", "619 M.", "10:1-109", "Story of Jonah – the accepted repentance", "Yunus'un kıssası; tüm bir milletin tövbesi kabul edildi"],
    [52, 11, "هود", "Hud", "Hud", "Mekke", "619 M.", "11:1-123", "Stories of prophets after Quraysh continued mockery", "Kureyş inadına karşı birçok peygamber kıssası"],
    [53, 12, "يوسف", "Yusuf", "Yusuf", "Mekke", "619 M.", "12:1-111", "Year of Sorrow: Khadija and Abu Talib die", "'Hüzün Yılı': Hz. Hatice ve Ebu Talip vefatı sırasında indi"],
    [54, 15, "الحجر", "Al-Hijr", "Hicr", "Mekke", "619 M.", "15:1-99", "Al-Hijr valley – Thamud, Lot's people", "Hicr bölgesi; Semud ve Lut kavminin helaki"],
    [55, 6, "الأنعام", "Al-Anam", "En'am", "Mekke", "619 M.", "6:1-165", "60 aspects of monotheism – revealed at once", "60 farklı tevhid delili; tek seferde tüm olarak indi"],
    [56, 37, "الصافات", "As-Saffat", "Saffat", "Mekke", "620 M.", "37:1-182", "Rows of angels – Ibrahim offers his son", "Saf saf melekler; İbrahim'in oğlunu kurban etmeye hazırlanması"],
    [57, 31, "لقمان", "Luqman", "Lokman", "Mekke", "620 M.", "31:1-34", "Luqman's wisdom to his son", "Lokman'ın oğluna nasihatleri: Allah'a ortak koşma, saygı göster"],
    [58, 34, "سبأ", "Saba", "Sebe", "Mekke", "620 M.", "34:1-54", "Kingdom of Sheba – blessings turned to loss", "Sebe melikesinin şükran etmediği nimet kavramı"],
    [59, 39, "الزمر", "Az-Zumar", "Zümer", "Mekke", "620 M.", "39:1-75", "Groups entering paradise and hellfire", "Cennet ve cehennem gruplarının tasviri; ihlasla ibadet"],
    [60, 40, "غافر", "Ghafir", "Mümin", "Mekke", "620 M.", "40:1-85", "The Forgiver – believer from Pharaoh's family", "Firavun'un ailesinden gizli mü'min; günahları bağışlayan Allah"],
    [61, 41, "فصلت", "Fussilat", "Fussilet", "Mekke", "620 M.", "41:1-54", "Verses spelled out – Ad and Thamud warned", "Arapça açıklanan vahiy; Ad ve Semud'a uyarı"],
    [62, 42, "الشورى", "Ash-Shura", "Şura", "Mekke", "620 M.", "42:1-53", "Consultation – revelation to all prophets", "İstişare emri; tüm peygamberlere gelen ortak vahiy"],
    [63, 43, "الزخرف", "Az-Zukhruf", "Zuhruf", "Mekke", "620 M.", "43:1-89", "Gold Ornaments – Jesus not divine", "Altın süsler; İsa'nın ilah olmadığının ispatı"],
    [64, 44, "الدخان", "Ad-Dukhan", "Duhan", "Mekke", "620 M.", "44:1-59", "The Smoke – famine and Day of Judgment", "Mekke'yi kaplayan duman belası; kıyamet"],
    [65, 45, "الجاثية", "Al-Jathiyah", "Casiye", "Mekke", "620 M.", "45:1-37", "The Kneeling – every nation has its record", "Her millet diz çökmüş; amel defterleri açılıyor"],
    [66, 46, "الأحقاف", "Al-Ahqaf", "Ahkaf", "Mekke", "621 M.", "46:1-35", "Sand Dunes – Ad people destroyed", "Ad kavminin yaşadığı Ahkaf bölgesi; inkara karşı ibret"],
    [67, 51, "الذاريات", "Adh-Dhariyat", "Zariyat", "Mekke", "621 M.", "51:1-60", "Winnowing Winds – Ibrahim hosts angels", "Dağıtan rüzgarlar; İbrahim'e gelen melek misafirler"],
    [68, 88, "الغاشية", "Al-Ghashiyah", "Gaşiye", "Mekke", "621 M.", "88:1-26", "The Overwhelming Event – faces humbled or joyful", "O gün bazı yüzler eğilmiş, bazıları pırıl pırıl"],
    [69, 18, "الكهف", "Al-Kahf", "Kehf", "Mekke", "621 M.", "18:1-110", "People of the Cave – protection story for Quraysh", "Mağara Ashابı; Deccal sorusuna cevap; Hızır-Musa kıssası"],
    [70, 16, "النحل", "An-Nahl", "Nahl", "Mekke", "621 M.", "16:1-128", "The Bees – gratitude for nature's blessings", "Arının vahyine işaret; nimete şükür"],
    [71, 71, "نوح", "Nuh", "Nuh", "Mekke", "621 M.", "71:1-28", "Noah's 950 years of patient calling", "Nuh'un 950 yıllık tebliğ ve sabrı; inkarcı kavim helak"],
    [72, 14, "إبراهيم", "Ibrahim", "İbrahim", "Mekke", "621 M.", "14:1-52", "Ibrahim's prayer for Mecca and his offspring", "İbrahim'in Mekke için ve zürriyeti için duası"],
    [73, 21, "الأنبياء", "Al-Anbiya", "Enbiya", "Mekke", "621 M.", "21:1-112", "The Prophets – chain of prophethood", "Peygamberler zinciri; tevhid mesajının sürekliliği"],
    [74, 23, "المؤمنون", "Al-Mu'minoon", "Mü'minun", "Mekke", "622 M.", "23:1-118", "Qualities of true believers before Hijra", "Hicret öncesi gerçek mü'minlerin özellikleri"],
    [75, 32, "السجدة", "As-Sajdah", "Secde", "Mekke", "622 M.", "32:1-30", "The Prostration – Quran's truth vs denial", "Kuran'ın gerçekliği; secde ve ihya gecesi ibadeti"],
    [76, 52, "الطور", "At-Tur", "Tur", "Mekke", "622 M.", "52:1-49", "Mount Sinai oath – Day of Judgment certain", "Tur dağı yemini; cennet ve cehennemin kesinliği"],
    [77, 67, "الملك", "Al-Mulk", "Mülk", "Mekke", "622 M.", "67:1-30", "Sovereignty – seven heavens, death as test", "Gökyüzünün yedi katı; ölüm-yaşam sınavı"],
    [78, 69, "الحاقة", "Al-Haqqah", "Hakka", "Mekke", "622 M.", "69:1-52", "The Inevitable – Ad and Thamud destroyed", "Kaçınılmaz saat; Ad ve Semud'un şiddetli azabı"],
    [79, 70, "المعارج", "Al-Ma'arij", "Mearic", "Mekke", "622 M.", "70:1-44", "Ascending Stairways – angels ascend to God", "Meleklerin 50.000 yıllık yükseliş yolu; sabır emri"],
    [80, 78, "النبأ", "An-Naba", "Nebe", "Mekke", "622 M.", "78:1-40", "The Great News – resurrection debated", "İnsanların tartıştığı büyük haber: dirilme gerçeği"],
    [81, 79, "النازعات", "An-Naziat", "Naziat", "Mekke", "622 M.", "79:1-46", "Those who drag forth – Pharaoh's fate", "Ruhları çekip çıkaranlar; Firavunun hazıra ibret olması"],
    [82, 82, "الانفطار", "Al-Infitar", "İnfitar", "Mekke", "622 M.", "82:1-19", "Sky cleaves apart – deeds recorded", "Göğün yarılması; her amelin kayıt altında olması"],
    [83, 84, "الانشقاق", "Al-Inshiqaq", "İnşikak", "Mekke", "622 M.", "84:1-25", "Sky splits – believer's easy reckoning", "Göğün çatlayıp inşikakı; mü'mine kolay hesap"],
    [84, 30, "الروم", "Ar-Rum", "Rum", "Mekke", "622 M.", "30:1-60", "Romans defeated – but will win in few years", "Romalıların yenilgisi ama birkaç yıl sonra galip geleceklerine dair kehanet"],
    [85, 29, "العنكبوت", "Al-Ankabut", "Ankebut", "Mekke", "622 M.", "29:1-69", "The Spider – trial before Hijra", "Hicret öncesi son Mekke suresi; sıkıntı sınavı"],
    [86, 83, "المطففين", "Al-Mutaffifeen", "Mutaffifin", "Mekke", "622 M.", "83:1-36", "Defrauders – cheat in weighing", "Ölçü hilekarlarına vay; yerinde yeter cezası"],
    // Medinan Surahs
    [87, 2, "البقرة", "Al-Baqarah", "Bakara", "Medine", "622-624 M.", "2:1-286", "After Hijra – longest surah, Qibla changed to Mecca", "Hicret sonrası en uzun sure; kıble Mescid-i Aksa'dan Kabe'ye döndürüldü"],
    [88, 8, "الأنفال", "Al-Anfal", "Enfal", "Medine", "624 M.", "8:1-75", "Battle of Badr – first major battle", "Bedir Savaşı: 313 mü'min 1000 müşriki yendi"],
    [89, 3, "آل عمران", "Al-Imran", "Al-i İmran", "Medine", "625 M.", "3:1-200", "Battle of Uhud – lessons from setback", "Uhud Savaşı'nın muhasebesini yaptı"],
    [90, 33, "الأحزاب", "Al-Ahzab", "Ahzab", "Medine", "627 M.", "33:1-73", "Battle of the Trench – coalition defeated", "Hendek Savaşı: 10.000 kişilik koalisyon mağlup edildi"],
    [91, 60, "الممتحنة", "Al-Mumtahinah", "Mümtehine", "Medine", "628 M.", "60:1-13", "Treaty of Hudaybiyyah – relations with disbelievers", "Hudeybiye Antlaşması sürecinde müşriklerle ilişkiler"],
    [92, 4, "النساء", "An-Nisa", "Nisa", "Medine", "625-626 M.", "4:1-176", "Uhud aftermath – women and family laws", "Uhud sonrası dul ve yetimlerin haklarını düzenleyen ayetler"],
    [93, 99, "الزلزلة", "Az-Zalzalah", "Zilzal", "Medine", "626 M.", "99:1-8", "The Earthquake – atom's weight of good", "Zerre ağırlığı amel bile hesapta; yerin titremesi"],
    [94, 57, "الحديد", "Al-Hadid", "Hadid", "Medine", "626 M.", "57:1-29", "Iron – spend in God's cause", "Demir'in yaratılışı; Allah yolunda infak çağrısı"],
    [95, 47, "محمد", "Muhammad", "Muhammed", "Medine", "624 M.", "47:1-38", "Rules of warfare after Badr", "Bedir'in ardından savaş hükümleri ve esir kanunu"],
    [96, 13, "الرعد", "Ar-Ra'd", "Ra'd", "Medine", "625 M.", "13:1-43", "Thunder glorifies God – Quran's authenticity", "Gök gürültüsü Allah'ı tesbih eder; Kuran'ın hakikat olduğunun delili"],
    [97, 55, "الرحمن", "Ar-Rahman", "Rahman", "Medine", "626 M.", "55:1-78", "The Beneficent – which of God's favors denied?", "Rahman'ın 31 kez tekrarlanan sorusu: 'Rabbinizin hangi nimetlerini yalanlarsınız?'"],
    [98, 76, "الإنسان", "Al-Insan", "İnsan", "Medine", "626 M.", "76:1-31", "Man created – reward for feeding the poor", "İnsan'ın yaratılışı; yoksulu, yetimi, esiri doyurmanın mükafatı"],
    [99, 65, "الطلاق", "At-Talaq", "Talak", "Medine", "627 M.", "65:1-12", "Divorce laws – treat women with kindness", "Boşanmada adalet ve kadına muamele hükümleri"],
    [100, 98, "البينة", "Al-Bayyinah", "Beyyine", "Medine", "627 M.", "98:1-8", "The Clear Proof – People of the Book and pagans", "Ehl-i Kitap ve müşriklere açık delil geldi"],
    [101, 59, "الحشر", "Al-Hashr", "Haşr", "Medine", "625 M.", "59:1-24", "Exile of Banu Nadir – Jewish tribe expelled", "Müslümanlarla antlaşmayı bozan Beni Nadir Yahudileri Medine'den sürgün edildi"],
    [102, 24, "النور", "An-Noor", "Nur", "Medine", "626 M.", "24:1-64", "The Light – after slander of Aisha", "Hz. Aişe'ye yapılan ifk iftirası üzerine indi; iffet hükümleri"],
    [103, 22, "الحج", "Al-Hajj", "Hac", "Medine", "626 M.", "22:1-78", "The Pilgrimage – Ibrahim called to Hajj", "İbrahim'in hacca çağırması; Kabe'nin kuruluşu"],
    [104, 63, "المنافقون", "Al-Munafiqoon", "Münafikun", "Medine", "626 M.", "63:1-11", "The Hypocrites exposed in Medina", "Medine'deki münafıkların maskesi düşürüldü"],
    [105, 58, "المجادلة", "Al-Mujadila", "Mücadele", "Medine", "627 M.", "58:1-22", "The Pleading Woman – zihar divorce", "Kocasından zihar yoluyla boşanan kadının davası"],
    [106, 49, "الحجرات", "Al-Hujurat", "Hucurat", "Medine", "628 M.", "49:1-18", "Etiquette – verify news, avoid suspicion", "Haber teyidi; zan ve gıybet yasağı"],
    [107, 66, "التحريم", "At-Tahrim", "Tahrim", "Medine", "628 M.", "66:1-12", "Prophet's household – sincere repentance", "Hz. Peygamberin hane hayatından ibret; samimi tövbe"],
    [108, 64, "التغابون", "At-Taghabun", "Tegabün", "Medine", "628 M.", "64:1-18", "Mutual Disillusion – family can be enemy", "Karşılıklı aldanma günü; aile mihnetlerine karşı sabır"],
    [109, 61, "الصف", "As-Saf", "Saf", "Medine", "628 M.", "61:1-14", "The Ranks – fight in God's cause like a solid wall", "Allah yolunda saf halinde savaş; İsa'nın Ahmed müjdesi"],
    [110, 62, "الجمعة", "Al-Jumu'ah", "Cuma", "Medine", "628 M.", "62:1-11", "Friday Prayer – congregational worship", "Cuma namazının farziyeti"],
    [111, 48, "الفتح", "Al-Fath", "Fetih", "Medine", "628 M.", "48:1-29", "Treaty of Hudaybiyyah – manifest victory", "Hudeybiye Antlaşması, açık bir fetih olarak nitelendi"],
    [112, 5, "المائدة", "Al-Maidah", "Maide", "Medine", "629-630 M.", "5:1-120", "The Table Spread – final rulings of Sharia", "Şeriatın son hükümleri; Veda Haccı öncesi indi"],
    [113, 9, "التوبة", "At-Tawbah", "Tevbe", "Medine", "630-631 M.", "9:1-129", "Repentance – after Conquest of Mecca", "Mekke'nin Fethi sonrası müşriklerle ilişkilerin son hükmü"],
    [114, 110, "النصر", "An-Nasr", "Nasr", "Medine", "631-632 M.", "110:1-3", "Divine Help – people enter Islam in multitudes", "Veda'nın habercisi: insanlar dalga dalga İslam'a girecek"],
];

function coord(i, period) {
    if (period === 'Mekke') {
        const col = i % 9;
        const row = Math.floor(i / 9);
        return [col * 5 - 20, 0, row * 5 - 20];
    } else {
        const mi = i - 86;
        const col = mi % 7;
        const row = Math.floor(mi / 7);
        return [col * 5 + 25, 0, row * 5 - 10];
    }
}

const result = surahs.map((s, i) => ({
    id: s[0],
    surahNumber: s[1],
    surahName: { ar: s[2], en: s[3], tr: s[4] },
    period: s[5],
    year: s[6],
    revelationOrder: s[0],
    verses: s[7],
    event: { en: s[8], tr: s[9] },
    context: { en: s[8], tr: s[9] },
    coordinates: coord(i, s[5])
}));

fs.writeFileSync(
    __dirname + '/../src/data/quranChronology.json',
    JSON.stringify(result, null, 2)
);
console.log(`✅ Generated ${result.length} surahs`);
